spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mail:
  smtp:
    auth: true
    starttls:
      enable: true
    host: smtp-relay.brevo.com
    port: 587
    ssl:
      trust: smtp-relay.brevo.com
    username: ENC(sJVtsL+EAH+WNrQ9kN0R0Rt+QrdcawHdnY9P3aRiA96YqVIZyfZ0gw==)
    from: no_replay@victoranchondo.com
    password: ENC(pPwcntUESIURcyTkD4EQQXpx1MzSU55wDG8HIju08PYmqWD+IRNQyXjaV7jk21/oxpBI98BeMm+ajRJ2SOBwYjx/GPC7spc9wMAVaZValwj05YBfiOYqEZ8y3FsaV+Qbthq4VRgRZCk=)

com:
  vanchondo:
    recaptcha:
      endpoint: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s&remoteip=%s
      secret: ENC(OgI39ZGk6+gw2EWJZrjQ2AH7SlPS2449EYJ9/fP5rg+fnBROWuKVsPF2miDbYBEJSKE5rDGEtFI=)
      threshold: 0.5
      max_attempt: 4
      max_attempt_expiration: 4
    login:
      issuer: sso-svc
      # Minutes
      expirationToken: 1440

      unsecuredUrls:
        - url: /swagger*
          methods: GET
        - url: /v2/api-docs
          methods: GET
        - url: /login
          methods: POST
        - url: /validate
          methods: POST
        - url: /register
          methods: POST
        - url: /regex
          methods: GET
        - url: /users/available
          methods: GET
