spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mail:
  smtp:
    auth: true
    starttls:
      enable: true
    host: smtp-mail.outlook.com
    port: 587
    ssl:
      trust: smtp-mail.outlook.com
    username: ENC(Gjn/ileOQ4s7FaVYYWykG1tSC2ZXWAxTZGCtd3BovsLN0Kzv81XRDQ==)
    password: ENC(4urs70afj8Avx+BgLkZQ2jhfCOv2O2DZweXWziq2aNc=)

com:
  vanchondo:
    recaptcha:
      endpoint: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s&remoteip=%s
      secret: ENC(OgI39ZGk6+gw2EWJZrjQ2AH7SlPS2449EYJ9/fP5rg+fnBROWuKVsPF2miDbYBEJSKE5rDGEtFI=)
      threshold: 0.5
      max_attempt: 4
      max_attempt_expiration: 4
    login:
      issuer: sso-svc
      # Minutes
      expirationToken: 1440

      unsecuredUrls:
        - url: /swagger*
          methods: GET
        - url: /v2/api-docs
          methods: GET-
        - url: /login
          methods: POST
        - url: /validate
          methods: POST
        - url: /register
          methods: POST
        - url: /regex
          methods: GET
        - url: /users/available
          methods: GET
