spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

com:
  vanchondo:
    login:
      issuer: sso-svc
      # Minutes
      expirationToken: 1440

      unsecuredUrls:
        - url: /login
          methods: POST
        - url: /register
          methods: POST
        - url: /users/available
          methods: GET
        - url: /swagger*
          methods: GET
        - url: /v2/api-docs
          methods: GET