jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: ENC(M/XDcwP4PSJ8aPTulgwR20hN8ql2VO8b)
    key-alias: sso-svc
    enabled: true
  port: 8443

spring:
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@192.168.3.8:27017/?retryWrites=true&w=majority
      database: sso
      username: ENC(fnSskThAoaH64tJdfjlJQiilCOIHXiuH)
      password: ENC(FurzDJnIQj+2f1P3mGyscq300lFDHuLY/rJn5eQVGpM=)

com:
  vanchondo:
    login:
      secretKey: ENC(q5X1D4JC2mH1b7IBcDpMu3ZpKAW9tWkp03Qgj9+5M5VmigUqrekNyTM47uE+Q0PU2ehDpsfIZpz7mAtefrQkyX3Hvmnslfwhc6PXUpf1G4U=)